cos_registration_server/api/urls.py
"""API urls."""

from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from . import views

app_name = "api"

urlpatterns = [
    # make a version API url
    path("v1/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "v1/docs/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="docs",
    ),
    path("v1/health/", views.HealthView.as_view(), name="health"),
    path("v1/devices/", views.DevicesView.as_view(), name="devices"),
    path("v1/devices/<str:uid>/", views.DeviceView.as_view(), name="device"),
    path(
        "v1/devices/<str:uid>/certificate/",
        views.DeviceCertificateView.as_view(),
        name="device_certificate",
    ),
    path(
        "v1/applications/grafana/dashboards/",
        views.GrafanaDashboardsView.as_view(),
        name="grafana_dashboards",
    ),
    path(
        "v1/applications/grafana/dashboards/<str:uid>/",
        views.GrafanaDashboardView.as_view(),
        name="grafana_dashboard",
    ),
    path(
        "v1/applications/foxglove/dashboards/",
        views.FoxgloveDashboardsView.as_view(),
        name="foxglove_dashboards",
    ),
    path(
        "v1/applications/foxglove/dashboards/<str:uid>/",
        views.FoxgloveDashboardView.as_view(),
        name="foxglove_dashboard",
    ),
    path(
        "v1/applications/prometheus/alert_rules/",
        views.PrometheusAlertRuleFilesView.as_view(),
        name="prometheus_alert_rule_files",
    ),
    path(
        "v1/applications/prometheus/alert_rules/<str:uid>/",
        views.PrometheusAlertRuleFileView.as_view(),
        name="prometheus_alert_rule_file",
    ),
    path(
        "v1/applications/loki/alert_rules/",
        views.LokiAlertRuleFilesView.as_view(),
        name="loki_alert_rule_files",
    ),
    path(
        "v1/applications/loki/alert_rules/<str:uid>/",
        views.LokiAlertRuleFileView.as_view(),
        name="loki_alert_rule_file",
    ),
]

cos_registration_server/cos_registration_server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("api/", include("api.urls")),
    path("devices/", include("devices.urls")),
    path("admin/", admin.site.urls),
]

cos_registration_server/devices/urls.py
"""Devices urls."""

from django.urls import path

from . import views

app_name = "devices"

urlpatterns = [
    path("", views.devices.as_view(), name="devices"),
    path("<str:uid>", views.device, name="device"),
]

cos_registration_server/devices/models.py
"""Device DB model."""

from applications.models import (
    FoxgloveDashboard,
    GrafanaDashboard,
    LokiAlertRuleFile,
    PrometheusAlertRuleFile,
)
from django.db import models


class Device(models.Model):
    """Device model.

    This class represent a device in the DB.

    uid: Unique ID of the device.
    creation_date: Creation date of the device.
    address: IP address of the device.
    public_ssh_key: device public SSH key.
    grafana_dashboards: Grafana dashboards relations.
    foxglove_dashboards: Foxglove dashboards relations.
    prometheus_alert_rule_files: Prometheus alert rules files relations.
    """

    uid = models.CharField(max_length=200, unique=True)
    creation_date = models.DateTimeField("creation date", auto_now_add=True)
    address = models.GenericIPAddressField("device IP")
    public_ssh_key = models.TextField("device public SSH key", default="")
    grafana_dashboards = models.ManyToManyField(
        GrafanaDashboard, related_name="devices"
    )
    foxglove_dashboards = models.ManyToManyField(
        FoxgloveDashboard, related_name="devices"
    )
    prometheus_alert_rule_files = models.ManyToManyField(
        PrometheusAlertRuleFile, related_name="devices"
    )
    loki_alert_rule_files = models.ManyToManyField(
        LokiAlertRuleFile, related_name="devices"
    )

    def __str__(self) -> str:
        """Str representation of a device."""
        return self.uid


class DeviceCertificate(models.Model):
    """Device Certificate model.

    This class represents a device certificate in the DB.

    device: OneToOne relationship to Device.
    csr: Certificate Signing Request in PEM format.
    certificate: Signed certificate in PEM format (null until signed).
    ca: CA that signed the certificate.
    chain: Certificate chain in PEM format.
    status: Current status of the certificate request.
    created_at: Timestamp when certificate request was created.
    updated_at: Timestamp when certificate was last updated.
    """

    class CertificateStatus(models.TextChoices):
        """Certificate request status choices."""

        PENDING = "pending", "Pending"
        SIGNED = "signed", "Signed"
        DENIED = "denied", "Denied"

    device = models.OneToOneField(
        Device,
        on_delete=models.CASCADE,
        related_name="certificate",
        primary_key=True,
    )
    csr = models.TextField("Device Certificate Signing Request")
    certificate = models.TextField(
        "Signed Device Certificate", blank=True, default=""
    )
    ca = models.TextField(
        "Device Certificate Authority", blank=True, default=""
    )
    chain = models.TextField(
        "Device Certificate Chain", blank=True, default=""
    )
    status = models.CharField(
        max_length=20,
        choices=CertificateStatus.choices,
        blank=True,
        default="",
    )
    created_at = models.DateTimeField(
        "Device Certificate request created", auto_now_add=True
    )
    updated_at = models.DateTimeField(
        "Device Certificate last updated", auto_now=True
    )

    def __str__(self) -> str:
        """Str representation of a certificate."""
        return f"Device Certificate for {self.device.uid}"

cos_registration_server/devices/views.py
"""Devices views."""

from typing import Any, Dict

from django.conf import settings
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.utils.http import urlencode
from django.views import generic

from .models import Device


class devices(generic.ListView):  # type: ignore[type-arg]
    """Devices list view."""

    template_name = "devices/devices.html"
    context_object_name = "devices_list"
    paginate_by = 20

    def get_queryset(self) -> Any:
        """Return all devices on GET."""
        return Device.objects.all()


def device(request: HttpRequest, uid: str) -> HttpResponse:
    """Device view.

    Representation of the device.

    uid: uid of the device passed by url.
    return: Http Response.
    """
    try:
        device = Device.objects.get(uid=uid)
    except Device.DoesNotExist:
        return HttpResponse(f"device {uid} not found")

    class ApplicationLinks:
        """Application links structure.

        This class is holding the links of an application
        so it can be passed to the html template.

        params:
            name: Name of the application.
            main_link: Main link of the application.
            additional_links: Additional links of the application
                    (dashboards etc).
        """

        def __init__(
            self,
            name: str,
            main_link: str,
            additional_links: Dict[str, str] = {},
        ) -> None:
            self.name = name
            self.main_link = main_link
            self.additional_links = additional_links

    base_url = request.META["HTTP_HOST"]

    cos_model_name = settings.COS_MODEL_NAME

    # fmt: off
    grafana_main_link = (
        f"{base_url}/{cos_model_name}-grafana/"
        f"dashboards/"
    )
    # fmt: on

    grafana_dashboards = {}
    grafana_param = {"var-Host": uid}
    for grafana_dashboard in device.grafana_dashboards.all():
        grafana_dashboards[grafana_dashboard.uid] = (
            base_url
            + f"/{cos_model_name}-grafana/d/"
            + grafana_dashboard.uid
            + "/"
            f"?{urlencode(grafana_param)}"
        )

    websocket_scheme = "wss" if request.scheme == "https" else "ws"

    foxglove_params = {
        "ds": "foxglove-websocket",
        "ds.url": f"{websocket_scheme}://{device.address}:8765",
    }
    foxglove_main_link = (
        f"{base_url}/"
        f"{cos_model_name}-foxglove-studio/?{urlencode(foxglove_params)}"
    )
    foxglove_layouts = {}
    for foxglove_dashboard in device.foxglove_dashboards.all():
        foxglove_params["layoutUrl"] = (
            f"{base_url}/{cos_model_name}-cos-registration-server/api/v1/"  # noqa: E501
            f"applications/foxglove/dashboards/{foxglove_dashboard.uid}"
        )
        foxglove_layouts[foxglove_dashboard.uid] = (
            f"{base_url}/{cos_model_name}-foxglove-studio/"
            f"?{urlencode(foxglove_params)}"
        )

    bag_files = f"{base_url}/{cos_model_name}-ros2bag-fileserver/{uid}/"

    links = []
    links.append(
        ApplicationLinks(
            "Foxglove studio", foxglove_main_link, foxglove_layouts
        )
    )
    links.append(
        ApplicationLinks("Grafana", grafana_main_link, grafana_dashboards)
    )
    links.append(ApplicationLinks("Bag files", bag_files))
    context = {
        "devices_list": Device.objects.all(),
        "device": device,
        "links_list": links,
    }
    return render(request, "devices/device.html", context)

cos_registration_server/devices/templates/devices/device.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Devices</title>

     <link rel="stylesheet" href="{% static 'css/vanilla-framework-version-4.11.0.min.css' %}" />

     <style>
       .l-application .u-fixed-width {
         max-width: 95rem;
       }

       .demo-status {
         padding-top: 0.75rem;
         padding-bottom: 0.75rem;
       }

       .is-cos-background {
         background-image: linear-gradient(180deg, #241f2b 0%, #181621 100%);
       }

       .is-cos-background .p-panel__logo-icon,
       .is-cos-background .p-panel__logo-name,
       .is-cos-background .p-panel__toggle,
       .is-cos-background .p-side-navigation__link,
       .is-cos-background .p-side-navigation__text {
         color: #fff;
       }

       .is-cos-background .p-panel__logo-name {
         margin-left: 0.5rem;
       }

       .is-cos-background .p-side-navigation__link:hover,
       .is-cos-background .p-side-navigation__link:focus {
         color: #f99b11;
       }

       .p-main-table {
         width: 100%;
       }
     </style>

     <link rel="icon" href="https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg" type="image/svg+xml" />

   </head>


  <body class="is-paper">
    <div class="l-application" role="presentation">
        <div class="l-navigation-bar">
          <div class="p-panel is-dark is-cos-background">
            <div class="p-panel__header">
              <a class="p-panel__logo" href="../devices">
                <img class="p-panel__logo-icon" src="https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg" alt="" width="24" height="24">
                <span class="p-panel__logo-name is-fading-when-collapsed">COS for devices</span>
              </a>
              <div class="p-panel__controls">
                <span class="p-panel__toggle js-menu-toggle">Menu</span>
              </div>
            </div>
          </div>
        </div>

         <header class="l-navigation is-collapsed">
           <div class="l-navigation__drawer">
             <div class="p-panel is-dark is-cos-background">
               <div class="p-panel__header is-sticky">
                 <a class="p-panel__logo" href="../devices">
                   <img class="p-panel__logo-icon" src="https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg" alt="" width="24" height="24">
                   <span class="p-panel__logo-name is-fading-when-collapsed">COS for devices</span>
                 </a>
                 <div class="p-panel__controls u-hide--large">
                   <button class="p-button--base is-dark has-icon u-no-margin u-hide--medium js-menu-close"><i class="is-light p-icon--close"></i></button>
                   <button class="p-button--base is-dark has-icon u-no-margin u-hide--small js-menu-pin"><i class="is-light p-icon--pin"></i></button>
                 </div>
               </div>
               <div class="p-panel__content">
 
                  <nav class="p-side-navigation--icons" id="drawer-icons" aria-label="Main">
                    <ul class="p-side-navigation__list">
                      <li class="p-side-navigation__item">
                        <a class="p-side-navigation__link" href="../devices">
                            <span class="p-side-navigation__label">All devices</span>
                            <span class="p-side-navigation__status">
                              <i class="p-icon--success"></i>
                            </span>
                        </a>
                      </li>
                    </ul>
                     {% if devices_list %}
                     <ul class="p-side-navigation__list is-fading-when-collapsed">
                        <li class="p-side-navigation__item">
                          <span class="p-side-navigation__text"><strong>Devices</strong></span>
                        </li>

                       {% for item in devices_list %}
                       <li class="p-side-navigation__item{% if item.uid == device.uid %} is-active{% endif %}">
                         <a class="p-side-navigation__link" href="{% url 'devices:device' item.uid %}">
                           <span class="p-side-navigation__label">{{ item.uid }}</span>
                         </a>
                       </li>
                       {% endfor %}
                     </ul>
                     {% else %}
                     <ul class="p-side-navigation__list is-fading-when-collapsed">
                       <li class="p-side-navigation__item">
                         <span class="p-side-navigation__text">No devices are available.</span>
                       </li>
                     </ul>
                     {% endif %}
                     <ul class="p-side-navigation__list is-fading-when-collapsed">
                        <li class="p-side-navigation__item">
                          <a href="https://github.com/canonical/cos-registration-server/issues" class="p-side-navigation__link" target="_blank" rel="noreferrer">Report a bug</a>
                        </li>

                       <li class="p-side-navigation__item">
                         <a href="https://github.com/canonical/cos-registration-server/issues" class="p-side-navigation__link" target="_blank" rel="noreferrer">Feedback</a>
                       </li>
                     </ul>
                     <ul class="p-side-navigation__list is-fading-when-collapsed">

                      <li class="p-side-navigation__item">
                        <span class="p-side-navigation__text">
                          Version
                          <div class="p-side-navigation__status">
                            <span class="p-chip--caution is-readonly is-inline is-dense">Beta</span>
                          </div>
                        </span>
                      </li>
                    </ul>
                  </nav>


 
               </div>
             </div>
           </div>
         </header>


        <main class="l-main">
          <div class="p-panel">
             <div class="p-panel__header">
               <h4 class="p-panel__title">Device {{ device.uid }}</h4>
             </div>

            <div class="p-panel__content">
               <div class="u-fixed-width">
                   <table aria-label="Device details" class="p-main-table">
                    <thead>
                      <tr>
                        <th>Device</th>
                        <th>IP</th>
                        <th class="u-align--right">Created</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td data-test-column="uuid"><span class="u-truncate">{{ device.uid }}</span></td>
                        <td data-test-column="IP"><span class="u-truncate">{{ device.address }}</span></td>
                        <td class="u-align--right" data-test-column="Created">{{ device.creation_date }}</td>
                      </tr>
                    </tbody>
                  </table>

 
                 {% for application_link in links_list %}
                 <div class="u-fixed-width">
                   <table aria-label="{{ application_link.name }} links" class="p-main-table">
                     <thead>
                       <tr>
                          <th><a class="p-link--soft" href="{{ request.scheme }}://{{ application_link.main_link }}">{{ application_link.name }}</a></th>

                       </tr>
                     </thead>
                     <tbody>
                       {% for name, link in application_link.additional_links.items %}
                       <tr>
                         <td><a href="{{ request.scheme }}://{{ link }}">{{ name }}</a></td>
                       </tr>
                       {% endfor %}
                     </tbody>
                   </table>
                 </div>
                 {% endfor %}

               </div>
             </div>
           </div>
         </main>

       <script>

      /*
        Set up event handlers for application layout examples.
        This is for demo purposes only. Real applications should implement it within their application code.
      */
      function setupAppLayoutExamples() {
        var aside = document.querySelector('.l-aside');
        var navigation = document.querySelector('.l-navigation');

        var menuToggle = document.querySelector('.js-menu-toggle');
        var menuClose = document.querySelector('.js-menu-close');
        var menuPin = document.querySelector('.js-menu-pin');
        var asideOpen = document.querySelector('.js-aside-open');
        var asideClose = document.querySelector('.js-aside-close');
        var asideResize = document.querySelectorAll('.js-aside-resize');
        var asidePin = document.querySelector('.js-aside-pin');

        if (menuToggle) {
          menuToggle.addEventListener('click', function () {
            navigation.classList.toggle('is-collapsed');
          });
        }

        if (menuClose) {
          menuClose.addEventListener('click', function (e) {
            navigation.classList.add('is-collapsed');
            document.activeElement.blur();
          });
        }

        if (asideOpen) {
          asideOpen.addEventListener('click', function () {
            aside.classList.remove('is-collapsed');
          });
        }

        if (asideClose) {
          asideClose.addEventListener('click', function () {
            aside.classList.add('is-collapsed');
          });
        }

        [].slice.call(asideResize).forEach(function (button) {
          button.addEventListener('click', function () {

            var panel = document.getElementById(button.getAttribute('aria-controls'));
            if (panel) {
              panel.classList.remove('is-narrow');
              panel.classList.remove('is-medium');
              panel.classList.remove('is-wide');
              if (button.dataset.resizeClass) {
                panel.classList.add(button.dataset.resizeClass);
              }
            }
          });
        });

        if (menuPin) {
          menuPin.addEventListener('click', function () {
            navigation.classList.toggle('is-pinned');
            if (navigation.classList.contains('is-pinned')) {
              menuPin.querySelector('i').classList.add('p-icon--close');
              menuPin.querySelector('i').classList.remove('p-icon--pin');
            } else {
              menuPin.querySelector('i').classList.add('p-icon--pin');
              menuPin.querySelector('i').classList.remove('p-icon--close');
            }
            document.activeElement.blur();
          });
        }

        if (asidePin) {
          asidePin.addEventListener('click', function () {
            aside.classList.toggle('is-pinned');
            if (aside.classList.contains('is-pinned')) {
              asidePin.innerText = 'Unpin';
            } else {
              asidePin.innerText = 'Pin';
            }
          });
        }
      }

      setupAppLayoutExamples();
      </script>

  </body>
</html>